# Generated by Django 4.2 on 2023-04-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_alter_menu_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='main_menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='root_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_children', to='tree_menu.menuitem', verbose_name='Корневой пункт меню'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(default=1, max_length=100, verbose_name='slug меню'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem', verbose_name='Родительский пункт меню'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
