# Generated by Django 4.2 on 2023-04-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0003_remove_menuitem_main_menu_menuitem_root_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='root_menu',
        ),
    ]
