# Generated by Django 4.2 on 2023-04-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0005_alter_menuitem_options_remove_menuitem_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элементы меню'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='nesting_level',
        ),
    ]
