# Generated by Django 4.2 on 2023-04-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0006_alter_menuitem_options_remove_menuitem_nesting_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='title',
        ),
    ]
