# Generated by Django 4.2 on 2023-04-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0007_rename_name_menuitem_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('-parent',), 'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элементы меню'},
        ),
    ]
