# Generated by Django 4.2 on 2023-04-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0010_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Элемент меню', 'verbose_name_plural': 'Элементы меню'},
        ),
    ]
